---
- name: Install MySQL and create database
  hosts: mysql
  become: true
  roles:
    - mysql

- name: Install and Configure apache
  hosts: apache
  become: true
  gather_facts: false
  roles:
    - apache
